set number
syntax enable
colorscheme onedark
"colorscheme monokai
set cursorline
set ruler
set showmatch
set autoindent
set smartindent
set backspace=2
set clipboard=unnamed
set tabstop=4
set softtabstop=4
set shiftwidth=4
set hlsearch
set incsearch
set ignorecase
set smartcase
set noeb
set wildmenu
set wildmode=longest:list,full
set mouse=v
